Repository T3Voila/templavoilaplus, pull requests merged in 2022-09, with the labels that each got.

#429 [BUGFIX] non-admins can't add content
  Classes/Controller/Backend/PageLayoutController.php
Labels: Bug

#425 [TASK] PageModule CSS refactoring: no navbar class, no tables, more reuse
  Resources/Private/Language/Backend/PageLayout.xlf
  Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node.html
  Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node/ChildsTable.html
  Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node/TitleBar.html
  Resources/Private/Templates/Backend/Ajax/Clipboard.html
  Resources/Private/Templates/Backend/Ajax/ContentElements.html
  Resources/Private/Templates/Backend/Ajax/Trash.html
  Resources/Private/Templates/Backend/PageLayout/Show.html
  Resources/Public/JavaScript/PageLayout.js
  Resources/Public/StyleSheet/PageLayout.css
  Resources/Public/StyleSheet/pre11LTScompat/bootstrap337-button.css
  Resources/Public/StyleSheet/pre11LTScompat/bootstrap337-card.css
  Resources/Public/StyleSheet/pre11LTScompat/bootstrap337-navbar.css
  Resources/Public/StyleSheet/pre11LTScompat/overrides.css
Labels: Task

#430 [BUGFIX] ddev breaks processValue wraps
  Classes/Handler/Render/XpathRenderHandler.php
Labels: Bug

#431 [TASK] json settings output should be userSettings only
  Resources/Private/Templates/Backend/PageLayout/Show.html
  Resources/Public/JavaScript/PageLayout.js
Labels: Task

#434 [BUGFIX] PageRepository was moved to cms-core in 10LTS, not 9LTS
  Classes/Domain/Repository/PageRepository.php
Labels: Bug

#435 [BUGFIX] content edit modal title should accept HTML
  Resources/Public/JavaScript/PageLayout.js
Labels: Bug

#437 [BUGFIX] FCEs with no mapping create exception
  Classes/Service/ProcessingService.php
Labels: Bug

#438 [BUGFIX] error when server has sql_mode=only_full_group_by enabled
  Classes/Controller/Backend/ControlCenter/Update/TemplaVoilaPlus8Controller.php
Labels: Bug

#436 [TASK] page info flash messages have redundant entries and wrong icon
  Classes/Controller/Backend/PageLayoutController.php
  Classes/Domain/Repository/PageRepository.php
  Classes/Utility/IconUtility.php
Labels: Bug, Task

#440 [TASK] FCEs with no mapping error should be more visible
  Classes/Service/ProcessingService.php
  Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node.html
Labels: Task

#441 [BUGFIX] if node has same children multiple times it is not shown
  Classes/Service/ProcessingService.php
Labels: Bug

#442 [FEATURE] MappingConfiguration should allow LLL-names
  Classes/Handler/Configuration/MappingConfigurationHandler.php
Labels: Feature

#443 [FEATURE] new mapping type RowList
  Classes/Handler/Mapping/DefaultMappingHandler.php
Labels: Feature

#444 [BUGFIX] Argument 2 passed to IconUtility::mapRecordTypeToIconIdentifier() must be of the type array, null given
  Classes/Utility/IconUtility.php
Labels: Bug

#445 [FEATURE] add TSconfig additionalRecordData.<table> for BE node data attributes
  Classes/Service/ProcessingService.php
  Documentation/CreatingTemplateExtension/PageUserTsconfigReference/Index.rst
  Resources/Private/Partials/Backend/Handler/DoktypeDefaultHandler/Node.html
Labels: Feature
